In [1]:
import numpy as np
import pandas as pd

In [4]:
#string

country=['nepal','india','pakistan']
pd.Series(country)

0       nepal
1       india
2    pakistan
dtype: object

In [5]:
#integer

numbers=[70,80,90,]
pd.Series(numbers)

0    70
1    80
2    90
dtype: int64

In [7]:
#custom index

numbers=[70,80,90,]
subjects=['maths','science','english']
pd.Series(numbers,index=subjects)

maths      70
science    80
english    90
dtype: int64

In [9]:
#setting a name

marks=pd.Series(numbers,index=subjects,name='marks')
marks

maths      70
science    80
english    90
Name: marks, dtype: int64

In [13]:
#series from dict
marks={
    'maths':67,
    'science':80
}
marks_series=pd.Series(marks,name='Marks')
marks_series

maths      67
science    80
Name: Marks, dtype: int64

Series Attributes

In [14]:
#size
marks_series.size

2

In [15]:
#dtype
marks_series.dtype

dtype('int64')

In [16]:
#name
marks_series.name

'Marks'

In [17]:
#is_unique
marks_series.is_unique

True

In [18]:
#index
marks_series.index

Index(['maths', 'science'], dtype='object')

In [19]:
#values
marks_series.values

array([67, 80])

Series using read_csv

In [30]:
#with one col
df = pd.read_csv('/content/subs.csv')

series = df.squeeze("columns")
series

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [ ]:
#with two col

In [32]:
#with one col
df = pd.read_csv('/content/kohli_ipl.csv',index_col='match_no')

series = df.squeeze("columns")
series

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [33]:
#with one col
df = pd.read_csv('/content/bollywood.csv',index_col='movie')

series = df.squeeze("columns")
series

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object